name: thunderstruck
channels:
- conda-forge
dependencies:
- aeolus
- cartopy
- cmcrameri
- cmocean
- dask
- ffmpeg
- imageio-ffmpeg
- ipykernel
- ipywidgets
- iris>=3.2
- latlon23
- loguru
- matplotlib>=3.5
- metpy>=1.0
- nc-time-axis
- numpy
- pandas
- python>=3.12
- pip
- python-stratify
- tqdm
- xarray
